### ISSUE TITLE
Nomad OpenAPI spec available

### ISSUE THREAD

**Issue by DerekStrickland** [brandonc/tfpgen#1]
HI @brandonc 

Really excited about this project. I wanted to let you know that the [Nomad OpenAPI](https://github.com/hashicorp/nomad-openapi) project is available if you need/want an [OpenAPI spec](https://github.com/hashicorp/nomad-openapi/blob/main/v1/openapi.yaml) to use as a test case.

**Comment by brandonc** [comment]
This is great! When I think I have a complete schema implemented, this will be my test bed. Thanks for pointing this out.

**Comment by brandonc** [comment]
I [created a schema test](https://github.com/brandonc/tfpgen/blob/main/integration-tests/generate_test.go#L144) against the nomad OpenAPI definition for quotas. I'll continue to use Nomad as a good real world test. Thanks!
